### ISSUE TITLE
Point Grey SDK in Wily

### ISSUE THREAD

**Issue by mmyros** [jonnew/Oat#12]
Hi, have you been able to install Point Grey SDK in ubuntu 15.10? Two dependencies are missing from packages, 

```
libgtkmm-2.4-1c2a

libglademm-2.4-1c2a
```

 I have not been able to satisfy them by including trusty repository or even compiling from source. Here's what I get:
```

Unpacking libflycapture2 (2.9.3.13) over (2.9.3.13) ...
Preparing to unpack libflycapture-2.9.3.13_amd64-dev.deb ...
Unpacking libflycapture2-dev (2.9.3.13) over (2.9.3.13) ...
dpkg: dependency problems prevent configuration of libflycapture2:
 libflycapture2 depends on libgtkmm-2.4-1c2a; however:
  Package libgtkmm-2.4-1c2a:amd64 is not installed.
 libflycapture2 depends on libglademm-2.4-1c2a; however:
  Package libglademm-2.4-1c2a is not installed.
```

Thanks!

**Comment by jonnew** [comment]
Hmm, I have not tried. All my machines are 14.04 LTS. The [Travis build](https://travis-ci.org/jonnew/Oat) is on 12.04 LTS. 

Both of those libraries seem like they are only for the evaluation GUI, called 'flycap' -- its pretty funny that they have an SDK wrapped up with their evaluation GUI. 

To be clear, you are getting these dependency errors when running the install script provided with the FlyCapture SDK, correct?

**Comment by mmyros** [comment]
Yes, install_flycapture.sh.

I contacted their support and it appears that I will have to downgrade: 

> Ubuntu 15.10 removed the libgtkmm and libglademm packages which are
> dependencies of our FlyCapture2, and thus make them incompatible. We will
> eventually support Ubuntu 16.04, but currently the only solution is to roll
> back to 14.04. We are sorry for any inconvenience that might caused.
> 
> I have put you in the list and will provide you an update as soon as we have a
> new SDK for 16.04LTS available.

Maybe there is a way to bypass installation of some components, but it looks like each one checks for all the others to be present. Anyway, thanks for the feedback.

**Comment by mmyros** [comment]
I got around those issues by adding trusty repository in sources.list and using aptitude to resolve dependencies. Some packages related to Point Grey GUI did not install, but what did install was enough to compile Oat with pointgrey support.

The resolution of the camera is apparently too high though, the processing lags even without MOG. It seems like object detection is what is slowing things down. Will CUDA help with this?

Thanks!

**Comment by jonnew** [comment]
Great, maybe you could add that info to the README.md and send a pull request if you have time.

With respect to the lag, there are some components in Oat that are worse than others. This is qualitified here: https://github.com/jonnew/Oat/blob/master/test/perf/results.md

1. What camera are you using and what is its resolution? 
2. How fast can you serve frames with no processing? Are you sure that object detection is whats slowing things down?
3. If it really is the resolution, you can down-sample on the FPGA in the camera for a huge speedup at the cost of lower effective resolution. 
4. What frame rate are you after?

**Comment by mmyros** [comment]
I canl pull request, but it's kind of hacky. I had to remove unity and aptitude, not sure I'd recommend putting it in readme.

1) I am using a 5MP,2448 x 2048 Blackfly https://www.ptgrey.com/blackfly-50-mp-color-gige-poe-sony-imx264-2
2) fast, 22 fps I think. MOG slows it down dramatically, and object detection does though not as much. I did not time it but MOG+detection feels like 1fps, and bsub+detection seems like 5 fps.
3) I'd prefer to keep the resolution if possible, we ordered a Point Grey for that reason. Maybe we should just swap the camera for a lower-resolution, faster one if there is no other way.
4) I just want 22 fps

**Comment by jonnew** [comment]
I have a bunch to say to this, but can you open a new issue?

**Comment by mmyros** [comment]
https://github.com/jonnew/Oat/issues/14

**Comment by jonnew** [comment]
Thanks!

**Comment by mmyros** [comment]
Just so this is documented, I was able to compile the new version of Point Grey SDK (flycapture2-2.10.3.169-amd64-pkg.tgz) with no issues on both Ubuntu 16 and Debian testing.

**Comment by jonnew** [comment]
Excellent thanks for letting me know!
