### ISSUE TITLE
"character conversion failed" error

### ISSUE THREAD

**Issue by ilodor** [jonnew/Oat#16]
Calling any oat component in the terminal results in the message "Character conversion failed" and a failure of the component to start. Cmake does not return an actual version number but Oat installation was fresh of off github on 5/12 and everything compiled without warnings or errors. Based on a google search I believe this is a problem with boost program_option::store. The error appeared with Ubuntu 14.04.3 and boost version 1.59.0 but disappeared upon upgrading to boost 1.60.0.

**Comment by jonnew** [comment]
Thanks for reporting this.

1. The version number of any oat component can be found using `oat <subcommand> --version`
2. Since this seems to be a problem with boost, I probably won't fix it unless the issue becomes more pervasive and can't be solved with a boost upgrade.
