### ISSUE TITLE
Max area can be too small

### ISSUE THREAD

**Issue by mmyros** [jonnew/Oat#24]
I am using a high-resolution camera, and sometimes the rat is not identified when it is larger and is identified when it is smaller, see screens. Is there a way to increase max area? I think then this issue might be solved. Thanks!

![camc9filt](https://cloud.githubusercontent.com/assets/3022307/17148944/1f03f156-5337-11e6-9243-78f9d361387e.png)
![camc8filt](https://cloud.githubusercontent.com/assets/3022307/17148942/1f0198de-5337-11e6-800f-62327a1a57b1.png)
![camc7filt](https://cloud.githubusercontent.com/assets/3022307/17148945/1f053f20-5337-11e6-868d-6778ab8d4932.png)
![camc6filt](https://cloud.githubusercontent.com/assets/3022307/17148943/1f01ed02-5337-11e6-8933-0f7346bf02a6.png)

**Comment by jonnew** [comment]
Oops! Magic numbers are never great. That said, I don't have time to implement a real solution so I just upped the max area to 1e5 pixels... Suggestions on a better idea are appreciated. 

See if this dumb fix works for you, though.

Awesome maze, BTW.

**Comment by mmyros** [comment]
I think it works! I don't mind a solution like that. It may be useful at some point to introduce a multiplier, which could also work for oat-decorate. But that seems like it would create potential for bugs.

Thanks! Built it in my advisor's garage of plywood and two arduinos. The rats enjoy it!
