### ISSUE TITLE
Posisock error

### ISSUE THREAD

**Issue by mmyros** [jonnew/Oat#31]
Hello,

Issuing posisock command as in README results in the following error:
```

$ oat posisock rep pos tcp://*:5555
posisock[pos->*]: Required configuration value 'endpoint' was not specified.
```

**Comment by jonnew** [comment]
Hmm, the latest version of the README should be (automatically) updated to track changes to the command line options. It is created using a awk command:

https://github.com/jonnew/Oat/blob/master/doc/make-README.sh

Can you point me to the error in the README? I don't see it here: https://github.com/jonnew/Oat#position-socket

After the program options refactor, note that specialized help for a particular component subtype can be seen via `oat subcommand type --help` which will provided specialized information compared to `oat subcommand --help`. For instance, for `oat-posisock rep --help`, this is what I see

```
debug[0]$ oat posisock rep --help
Usage: posisock rep [INFO]
   or: posisock rep SOURCE [CONFIGURATION]
Send positions from SOURCE to a remote endpoint.

SOURCE:
  User-supplied name of the memory segment to receive positions from (e.g. pos).

INFO:
  --help                  Produce help message.
  -v [ --version ]        Print version information.

CONFIGURATION:
  -c [ --config ] arg     Configuration file/key pair.
                          e.g. 'config.toml mykey'

  -e [ --endpoint ] arg   ZMQ-style endpoint. For TCP: 
                          '<transport>://<host>:<port>'. For instance, 
                          'tcp://*:5555'. Or, for interprocess communication: 
                          '<transport>:///<user-named-pipe>. For instance 
                          'ipc:///tmp/test.pipe'.
```
which indicates that the endpoint must be specified via the `-e` switch.

**Comment by mmyros** [comment]
Ah I see it was just the example 

https://github.com/jonnew/Oat/pull/32
