### ISSUE TITLE
Is oat-frameserve able to use Firewire Point Gray camera IEEE1394b connection ?

### ISSUE THREAD

**Issue by lengoanhcat** [jonnew/Oat#35]
Hi,

I am working with the first-generation Point Grey grasshopper which uses Firewire connection instead of GiGE ? Is it possible to use Oat with these cameras and connection standards ? 

Regards,

Cat Le

**Comment by jonnew** [comment]
It might be, but I don't know how much they changed their API in the move the USB/USB3.0. The easiest way to find out is to try: `oat -frameserve usb raw`.

**Comment by lengoanhcat** [comment]
Thanks @jonnew, I confirm that I could use oat-frameserve to access stream data from PointGrey Grasshopper with IEEE1394b connection.

**Comment by jonnew** [comment]
Excellent!
